// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDePuTks7GxM9tf6X_ZIyBJiN-BdcXLUcA',
    appId: '1:789723547159:web:b922656cc755f5d70bfe52',
    messagingSenderId: '789723547159',
    projectId: 'openthebox-88085',
    authDomain: 'openthebox-88085.firebaseapp.com',
    storageBucket: 'openthebox-88085.appspot.com',
    measurementId: 'G-4W68FRESK2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQMcqCVoc-p17ANO07B_UrM4Rm38p9Q9A',
    appId: '1:789723547159:android:c1f3c99dbe1a312c0bfe52',
    messagingSenderId: '789723547159',
    projectId: 'openthebox-88085',
    storageBucket: 'openthebox-88085.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjeoUiw1CULgczmmkcSSNnEU7ipIbpxlE',
    appId: '1:789723547159:ios:a946a2bcd86047010bfe52',
    messagingSenderId: '789723547159',
    projectId: 'openthebox-88085',
    storageBucket: 'openthebox-88085.appspot.com',
    iosBundleId: 'com.example.openthebox',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjeoUiw1CULgczmmkcSSNnEU7ipIbpxlE',
    appId: '1:789723547159:ios:e32fe9401aaaf48b0bfe52',
    messagingSenderId: '789723547159',
    projectId: 'openthebox-88085',
    storageBucket: 'openthebox-88085.appspot.com',
    iosBundleId: 'com.example.openthebox.RunnerTests',
  );
}
